"""empty message

Revision ID: 25a4b4a867eb
Revises: 
Create Date: 2023-06-19 17:12:53.937302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a4b4a867eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nama', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kategori',
    sa.Column('id_kategori', sa.String(), nullable=False),
    sa.Column('nama_kategori', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_kategori')
    )
    op.create_table('pengguna',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('nama', sa.String(), nullable=True),
    sa.Column('kontak', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('role',
    sa.Column('id_role', sa.String(), nullable=False),
    sa.Column('nama_role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_role')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    op.drop_table('pengguna')
    op.drop_table('kategori')
    op.drop_table('course')
    # ### end Alembic commands ###
